---
title: "INF 550 Intro to NEON Exercises Part 2"
author: "Natasha Wesely"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE, warning=F, error=F}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(neonUtilities)
library(geoNEON)
library(sp)
```

# 2.14.1 Written
## Question 1
**How does NEON address ‘dark data’ (Chapter 1)?**

## Question 2
**How might or does the NEON project intersect with your current research or future career goals? (1 paragraph)**

## Question 3
Use the map in Chapter 2:Intro to NEON to answer the following questions. Consider the research question that you may explore as your final semester project or a current project that you are working on and answer each of the following questions:

**Are there NEON field sites that are in study regions of interest to you?**



**What domains are the sites located in?**



**What NEON field sites do your current research or Capstone Project ideas coincide with?**



**Is the site or sites core or relocatable?**



**Are they terrestrial or aquatic?**



**Are there data available for the NEON field site(s) that you are most interested in? What kind of data are available?**



## Question 4
Consider either your current or future research, or a question you’d like to address durring this course and answer each of the following questions:

**Which types of NEON data may be more useful to address these questions?**


**What non-NEON data resources could be combined with NEON data to help address your question?**


**What challenges, if any, could you foresee when beginning to work with these data?**



## Question 5
Use the Data Portal tools to investigate the data availability for the field sites you’ve already identified in the previous sections and answer each of the following questions:

**What types of aquatic or terrestrial data are currently available? Remote sensing data?**


**Of these, what type of data are you most interested in working with for your project during this course?**


**For what time period does the data cover?**


**What format is the downloadable file available in?**


**Where is the metadata to support this data?**



# 2.14.2 NEON Coding Lab Part 2


