---
title: "INF 550 Section 4.4"
author: "Natasha Wesely"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 4.4 Digital Repeat Photography Written Questions

## Question 1
**What do you see as the value of the images themselves? The 1 or 3-day products, the transition dates? How could they be used for different applications?**

I see the value of these images as chronicalling the changes of an ecosystem through time. The 30ish minute repeat photography is oversampling the region of interest. This kind of raw, noisy data could be useful for people who want to define their own region of interest within a photo. The 1 or 3 day cleaned data products are very nice for quick and easy use. This would be useful for people who are more interested in tracking the through time changes in greenness. The transition dates are also incredibly useful for people trying to track how climate change is affecting phenological shifts. 

## Question 2
**Why does PhenoCam take photos every 15-30 minutes, but summarize to 1 or 3-day products?**

The 15-30 minute data is just a lot of data. There is also a lot of noise in the 15-30 minute data. Often the cameras come on and start taking photos when it's still somewhat dark outside, and they don't stop taking photos until after sunset. The cleaner 1 or 3 day products take all the 15-30 minute data and remove a lot of images to get rid of noise and then average the the greenness. That way if there is one photo with randomly high greenness in a photo, that photo isn't giving a false representation of the area. 

## Question 3
**Why does canopy color coordinate with photosynthesis in many ecosystems? Name an example of a situation where it wouldn’t and explain why.**

Canopy color coordinates with photosynthesis in many ecosystems because most plants in most ecosystems are green (because they have chlorophyll). So you can make inferences about how much photosynthesis is going on (or how active the plant is, or how much the plant is growing) based on changes in the canopy colors.

Examples of situations where it wouldn't work to look at greeness: 

Some plants don't have green leaves, so measuring the GCC isn't going to tell you anything about how much that type of plant is growing. Lots of plants also change colors in the fall, so if you are wanting to know about how much plants are photosynthesizing in the fall, you need to look at something else besides greenness in the repeated photos.
Or if you are in a really foggy area, a lot (or all) of your photos are going to be too clouded to make any inferences about changing canopy color.


## Question 4
**Why are there sometimes multiple Regions of Interest (ROIs) for a PhenoCam?**

Because sometimes you are interested in more than one functional type of plant in the same photo. So you can make a ROI around some grass in a photo and analyze how the grass is changing, then you can make an ROI around some shrubs in the same photo and analyze the pixels associated with the shrubs.

## Question 5
**How might or does the PhenoCam project intersect with your current research or future career goals? (1 paragraph)**

I am trying to constrain a process-based model representing the major carbon and water cycle components in four different ecosystem types in the Sevilleta Wildlife Refuge area: a desert grassland, a plains grassland, a desert shrubland, and a juniper savanna.

I would like to incorporate phenocam data to help constrain some of the carbon pool parameters in my process-based model. Incorporating phenocam data could allow us to estimate phenolgical shifts, such as green-up and brown-down, which have major implications for the amount of photosynthesis going on and therefore the amount of carbon being sequestered. Once carbon “enters” the process-based model, it moves through the different plant issue and ultimately decomposes in the soil.
I want to take phenocam data about spring and fall phenological shifts on plants that match our four ecosystem types of interest from the same around as the Sevilleta Wildlife Refuge, curate the data, and feed in into the model-data fusion algorithms I am using to constrain the parameters in our process-based model.

## Question 6
**Use the map on the PhenoCam website to answer the following questions. Consider the research question that you may explore as your final semester project or a current project that you are working on and answer each of the following questions:**

**Are there PhenoCams that are in study regions of interest to you?**

Yes! There are phenocams in the Sevilleta Wildlife Refuge.

**Which PhenoCam sites does your current research or final project ideas coincide with?**

There are a lot! Here are a few

1) sevilletagrass
2) sevilletanewgrass
3) sevilletashrub
4) sevMRME10L


**Are they connected to other networks (e.g. LTAR, NEON, Fluxnet)?**

Yes, LTER and NEON.

**What is the data record length for the sites you’re interested in?**

They vary camera to camera

1) Start Date: 2014-11-05 (6 years)
2) Start Date: 2018-12-05 (4 years)
3) Start Date: 2014-10-29 (6 years)
4) Start Date: 2018-11-15 (4 years)

## Question 7
**Consider either your current or future research, or a question you’d like to address during this course:**

**Which types of PhenoCam data may be more useful to address these questions?**

For me, the 1 or 3 day data products are the most useful. The suggested phenological shift dates for green-up and brown-down would also be very useful for my research.

**What non-PhenoCam data resources could be combined to help address your question?**

I want to combine phenocam data with NEON data in my process-based model. The two different data streams could help inform different parameters in my process-based model.

**What challenges, if any, could you foresee when beginning to work with these data?**

Potential problems I foresee with this data is possibly false greenness, like thinking an image is super green when it was just a fluke. This could mess up my estimates of photosynthesis. However, the standard data cleaning protocol automatically happening within the phenocam website should protect against this for the most part. However, it would be good to keep an eye out for errors in my timeseries. 

