---
title: "INF 550 Section 6.14"
author: "Natasha Wesely"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# NEON AOP Written Questions
## Question 1
**What is the overlap in the type of data generated by NEON AOP and PhenoCam. What metrics from PhenoCam could you apply to NEON AOP data, especially once there are >10 years of aerial data?**

NEON AOP data and Phenocam data can both be used to quantify vegetation indices and changes in vegetation through time. We could apply transition dates derived from phenocam data to further analyze and/or enhance NEON AOP data, especially once there are more than 10 years of data and one can analyze how phenological transition dates are changing through time, most likely as a byproduct of climate change. 

## Question 2
**List 4 challenges to timing AOP flight campaigns.**

1) You have one sensor that is very expensive and mobile, so we have to decide when and where to move it. We can't afford to constantly be collecting data in this way. You have to be careful about when/where you send the plane to be economical.
2) The timing of when you fly over an area affects how some of the bands of data will be because the sun angle affects things like the RBG bands.
3) Artifacts in the AOP data from patching flight paths together
4) Missaligned flight paths that leave spacial gaps in the data


## Question 3
**When using NEON AOP data, when should you use byTileAOP versus byFileAOP? What additional processing might you need to do if you worked with the byFileAOP data? Hint: try pulling the data in both formats (this will take a while)**

The byTileAOP() function should be used when we only want data covering a certain area. The byTileAOP() queries for data tiles containing a specified list of coordinates. It only works for the tiled (mosaicked) versions of the remote sensing data.

The byFileAOP() function downloads remote sensing data based on data product, site, and year criteria. This function preserves the file structure of the original data. This function can take a VERY long time, depending on the data you request. So you should use the byFileAOP() when you are more interested in getting data based on product/site/year rather than a particular spatial area.


## Question 4
**How do the additional bands in NEON AOP improve our contraint of Biodiversity and Ecosystem Structure relative to satellite-derived data?**

Additional bands in the NEON AOP data give us more information about more attributes of an ecosystem besides simply presence/absence of vegetation or how green the vegetation is (the typical things one can derive from satellite data), such as vegetation structure. These additional attributes allow us to make more inferences different aspects of an ecosystem, such as biodiversity and ecosystem structure. For example, we get more infrared type bands from the NEON AOP that we can compare to satellite data. Having many bands also enables analyses where we combine more than one band to get a metric/proxy for something more interesting or accurate. 

## Question 5
**What role do campaigns such as NEON AOP play in ‘filling the sampling gap’ of essential in situ data such as FLUXNET (Eddy Co-Variance) data?**

Campaigns like NEON AOP help fill in the data sampling gap for eddy co-variance data by enabling the scale-up of eddy-covariance data to larger spatial regions. One can compare the AOP data over a specific flux tower, perhaps train a model related the two spatially overlapping data products, and then extrapolate using the model to larger spatial areas beyond the flux tower. 

Additionally, there are somethings you can't measure from space because the bands get essentially blocked by the atmosphere. So NEON AOP data can function as a bridge between flux tower data and satellite data.

## Question 6
**List 3 attributes of NEON AOP data that are unique to other publicly served data. Hints: Band width? Resolution? Something else?**

1) NEON AOP includes an imaging spectrometer covering 380–2,500 nm in 426 bands
2) NEON AOP has a 1 m spatial resolution
3) NEON AOP provides a reflectance product with a spectral sampling of ~5 nm

## Question 7
**Which data product(s) derived from the NEON AOP campaign align with remotely-sensed products from NASA? Hint: start with vegetation indices**

NEON AOP derive some of the exact same products from their data as other organizations like NASA. For example, NDVI is a classic vegetation index that most data organizations derive. 


