---
title: "INF 550 Section 6.15"
author: "Natasha Wesely"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lidR)

```

# NEON AOP Coding Lab
## Question 1
**1: How are these two forests similar? How are they different? (3-5 sentences)**

A few places to start if you need them. You don’t have to address these, just in case you need some hints: Climate? How that could affect vegetation structure? Heterogeniety of the ecossytems? How seasonal are they? (hint:PhenoCam) Something else?



## Question 2
**2: Using this NEON tutorial and the tutorials we’ve covered in this textbook (hint: you did half of this workflow in your very first coding lab) pull the NEON AOP derived Canopy Height Model (CHM, DP3.30015.001) and High-resolution orthorectified camera imagery mosaic DP3.30010.001 for each forest and overlay the NEON TOS Woody Vegetation Structure DP1.10098.001 basal diameter data product to evaluate how well AOP captures trees in each forest.**

Generate a labeled 2x2 plot panel including:

Each RGB image with basal diameter overlaid

Each CHM with basal diameter overlaid

Write 2-3 sentences summarizing your findings and thoughts.

## Question 3
**Use the byTileAOP function of the neonUtilities package to pull a subset of the descrete LiDAR pointcloud for each forest (Hint: You can feed byTileAOP Easting and Northing from your Vegetation Structure dataframe(s)). Use the structural_diversity_metrics function that you defined in section 6.5 of the textbook to process discrete return LiDAR for each site and generte structural diversity metrics.

Using lidR generate a labeled 2-panel plot of your canopy height model for each forest
Using lidR generate a labeled 2-panel plot of a cross-section for each forest
Use section 6.5.3 Comparing Metrics Between Forests to compare each forest and generate a a clean summary table via kable
Using Table 2 from LaRue, Wagner, et al. (2020) as a reference, write 1-2 paragraphs summarizing the differences in forest structural diversity between the two forests and how they may relate to your answers to Question 1.**
